version: 2
updates:
  # Enable version updates for pnpm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:00'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 10
    target-branch: 'main'
    assignees:
      - 'santosr2'
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps-dev'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    groups:
      # Group all TypeScript-related packages
      typescript:
        patterns:
          - '@types/*'
          - 'typescript'
          - 'ts-*'
          - '@typescript-eslint/*'
      # Group testing frameworks and related tools
      testing:
        patterns:
          - 'vitest'
          - '@vitest/*'
          - 'vitest-*'
          - 'c8'
          - 'coverage-*'
      # Group linting and formatting tools
      linting:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - 'eslint-*'
          - 'prettier'
          - 'prettier-*'
      # Group build and bundling tools
      build-tools:
        patterns:
          - '@vercel/ncc'
          - 'ncc'
          - 'rollup'
          - 'rollup-*'
          - 'esbuild'
          - 'webpack'
          - 'webpack-*'
      # Group GitHub Actions related dependencies
      github-actions:
        patterns:
          - '@actions/*'
          - 'actions-*'
    # Security updates get higher priority
    allow:
      - dependency-type: 'direct'
      - dependency-type: 'indirect'
    # Ignore specific packages that require manual review
    ignore:
      # Pin specific versions that we want to control manually
      - dependency-name: 'node'
        update-types: ['version-update:semver-major']
      # Handle major updates manually for critical packages
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Enable version updates for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:30'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 5
    target-branch: 'main'
    assignees:
      - 'santosr2'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'github-actions'
      - 'security'
      - 'automated'
    # Group actions by organization/purpose
    groups:
      # Group all actions from the same organization
      actions-org:
        patterns:
          - 'actions/*'
      github-org:
        patterns:
          - 'github/*'
      # Group security-related actions
      security-actions:
        patterns:
          - '*/codeql-action*'
          - '*/security-*'
          - 'aquasecurity/*'
          - 'codecov/*'
    # Allow all types of updates for security
    allow:
      - dependency-type: 'direct'
      - dependency-type: 'indirect'
