version: 2
updates:
  # Enable version updates for pnpm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:00'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 10
    assignees:
      - santosr2
    commit-message:
      prefix: 'deps'
      include: 'scope'
    groups:
      # Group development dependencies
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - '@types/*' # Type definitions get their own group
      # Group production dependencies
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      # Separate group for type definitions
      type-definitions:
        patterns:
          - '@types/*'
        update-types:
          - minor
          - patch
    # Security updates for all dependency types
    ignore:
      # Ignore major version updates (handled manually)
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Enable version updates for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:30'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 5
    assignees:
      - santosr2
    commit-message:
      prefix: 'ci'
      include: 'scope'
    # Group all GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
