# PR Labeler Configuration
# Automatically label PRs based on changed files

# Source Code Changes
'area:core':
  - changed-files:
      - 'src/lib/**'
      - 'src/main.ts'

'area:types':
  - changed-files:
      - 'src/file.ts'
      - 'src/**/*.ts'
      - 'types/**'

'area:tests':
  - changed-files:
      - '__tests__/**'
      - '**/*.test.ts'
      - '**/*.spec.ts'
      - 'vitest.config.ts'

'area:benchmarks':
  - changed-files:
      - '**/*.bench.ts'
      - 'benchmarks/**'

# Infrastructure & DevOps
'area:ci':
  - changed-files:
      - '.github/workflows/**'
      - '.github/actions/**'

'area:build':
  - changed-files:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tsconfig*.json'
      - 'dist/**'
      - 'scripts/**'
      - '.vercel/**'

'area:security':
  - changed-files:
      - '.github/workflows/security.yml'
      - '.github/workflows/codeql.yml'
      - '.gitleaks.toml'
      - 'SECURITY.md'

'area:deps':
  - changed-files:
      - 'package.json'
      - 'pnpm-lock.yaml'

# Documentation
'area:docs':
  - changed-files:
      - '**/*.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE/**'
      - 'CONTRIBUTING.md'
      - 'SECURITY.md'
      - 'CONTRIBUTORS.md'

'area:examples':
  - changed-files:
      - 'examples/**'
      - '.github/workflows/examples/**'

# Configuration
'area:config':
  - changed-files:
      - '.github/**'
      - '.gitignore'
      - '.prettierrc'
      - '.eslintrc*'
      - 'mise.toml'
      - '.mise.toml'
      - '.pre-commit-config.yaml'

'area:license':
  - changed-files:
      - 'LICENSE'
      - '.github/workflows/license.yml'

# Release & Distribution
'area:release':
  - changed-files:
      - '.github/workflows/release.yml'
      - 'CHANGELOG.md'
      - 'action.yml'

'area:sbom':
  - changed-files:
      - 'scripts/generate-sbom.js'
      - 'dist/sbom.json'

# Priority Labels
'priority:high':
  - changed-files:
      - 'SECURITY.md'
      - 'src/lib/action.ts'
      - 'action.yml'

'priority:low':
  - changed-files:
      - '**/*.md'
      - 'docs/**'
      - 'examples/**'

# Breaking Changes Indicators
'breaking-change':
  - changed-files:
      - 'action.yml' # Changes to action interface
      - 'src/lib/filter.ts' # Core filter logic changes

# Needs Review Labels
'needs:security-review':
  - changed-files:
      - '.github/workflows/**'
      - 'src/**/*.ts'
      - 'scripts/**'

'needs:docs-update':
  - changed-files:
      - 'action.yml'
      - 'src/lib/**'
      - 'package.json'
