# mise configuration for consistent toolchain management
# https://mise.jdx.dev/

[tools]
# Node.js version for local development (22) - CI tests both 22 and 24
# Runtime uses Node.js 24 (specified in action.yml)
node = "22"
# pnpm version matching packageManager field
pnpm = "10"
# Security scanning tool
gitleaks = "latest"
# Pre-commit hooks
pre-commit = "latest"

[env]
# Ensure pnpm uses the specified version
PNPM_VERSION = "10"
# Security scanning configuration
GITLEAKS_CONFIG = ".gitleaks.toml"
# Performance monitoring
NODE_OPTIONS = "--max-old-space-size=4096"

[tasks]
# Common development tasks
dev = "pnpm install && pnpm run dev"
build = "pnpm run build && pnpm run package"
test = "pnpm run test"
lint = "pnpm run lint"
check = "pnpm run check"
format = "pnpm run format"

# DevSecOps tasks
security = "gitleaks detect --source . --verbose"
license-check = "pnpm run license-check"
sbom = "pnpm run sbom"
vuln-scan = "pnpm audit --audit-level high"

# Documentation tasks
docs = "pnpm run docs"
docs-serve = "cd docs && python3 -m http.server 8080"

# Performance and quality
benchmark = "pnpm run test:bench"
coverage = "pnpm run test:coverage"
all-checks = "mise run format && mise run lint && mise run check && mise run security && mise run license-check && mise run test && mise run build"

# Release preparation
changelog = "pnpm conventional-changelog -p conventionalcommits -i CHANGELOG.md -s"
release-check = "mise run all-checks && mise run sbom && echo 'Release checks completed successfully'"

# DevSecOps validation
validate-devsecops = "./scripts/validate-devsecops.sh"
security-audit = "pnpm audit --audit-level high && mise run security && mise run license-check"
