# mise configuration for consistent toolchain management
# https://mise.jdx.dev/

[tools]
# Node.js version for local development (22) - CI tests both 22 and 24
# Runtime uses Node.js 24 (specified in action.yml)
node = "22"
# pnpm version matching packageManager field
pnpm = "10.15.1"
# Go for license header tooling
go = "1.24"
# Security scanning tools
gitleaks = "8.28.0"
# Pre-commit hooks
pre-commit = "latest"
# Documentation generation
"npm:typedoc" = "latest"
# Benchmarking tools for performance monitoring
"npm:@vitest/ui" = "latest"
# Act for local GitHub Actions testing
act = "latest"
# Shell script validation
shellcheck = "latest"

[env]
# Ensure pnpm uses the specified version
PNPM_VERSION = "10.15.1"
# Security scanning configuration
GITLEAKS_CONFIG = ".gitleaks.toml"
# Performance monitoring
NODE_OPTIONS = "--max-old-space-size=4096"
# Force color output in CI/CD environments
FORCE_COLOR = "1"
# Coverage thresholds
VITEST_MIN_COVERAGE = "80"
# CI environment detection - simple pass-through
CI = "${CI:-false}"

[tasks]
# Common development tasks
dev = "pnpm install && pnpm run dev"
build = "pnpm run build && pnpm run package"
test = "pnpm run test"
lint = "pnpm run lint"
check = "pnpm run check"
format = "pnpm run format"

# DevSecOps tasks
security = "gitleaks detect --source . --verbose"
license-check = "pnpm run license-check"
license-eye-install = "go install github.com/apache/skywalking-eyes/cmd/license-eye@latest"
license-headers-fix = "license-eye header fix"
license-headers-check = "license-eye header check"
vuln-scan = "pnpm audit --audit-level high"

# Documentation tasks
docs = "pnpm run docs"
docs-serve = "cd docs && python3 -m http.server 8080"

# Performance and quality
benchmark = "pnpm run bench"
coverage = "pnpm run coverage"
all-checks = "mise run format && mise run lint && mise run check && mise run security && mise run license-check && mise run test && mise run build"

# Act-based testing for examples
test-examples = "cd examples && act -l && echo 'Use: act <event> -W .github/workflows/examples/<workflow>.yml'"

# Release preparation
changelog = "pnpm conventional-changelog -p conventionalcommits -i CHANGELOG.md -s"
release-check = "mise run all-checks && mise run benchmark && echo 'Release checks completed successfully'"

# DevSecOps validation (NO SBOM - handled by CI only)
security-audit = "pnpm audit --audit-level high && mise run security && mise run license-check"
