name: 🤔 Question
description: Ask a question about using this action
title: '[Question]: '
labels:
  - question
  - needs-triage

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your question! Please fill out this template to help us provide the best answer.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have read the documentation and examples
          required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to achieve
      placeholder: |
        I'm trying to...
        My use case is...
    validations:
      required: true

  - type: textarea
    id: current-config
    attributes:
      label: Current Configuration
      description: If applicable, share your current workflow configuration
      render: yaml
      placeholder: |
        - uses: santosr2/conditional-paths-action@v3
          with:
            filters: |
              # your current configuration

  - type: textarea
    id: attempts
    attributes:
      label: What I've Tried
      description: What have you already tried? Include any error messages or unexpected behavior
      placeholder: |
        I tried...
        The result was...

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question fall under?
      options:
        - Filter configuration and syntax
        - Workflow integration
        - Output formats and usage
        - Performance and optimization
        - Troubleshooting errors
        - Best practices
        - Comparison with alternatives
        - Other (please specify in Additional Context)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context that might help answer your question
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
